version: '3'

services:
  traefik:
    image: traefik:v3.1.4
    command:
      - --api.insecure=true
      - --providers.docker
      - --entrypoints.web.address=:80

    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  go-server:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.go-server.rule=Host(`go-server.docker.localhost`)"
      - "traefik.http.routers.go-server.entrypoints=web"
      - "traefik.http.services.go-server-service.loadbalancer.server.port=8080"

  whoami:
    image: traefik/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"
